### ISSUE TITLE
Changing the UI background color

### ISSUE THREAD

**Issue by jaskirat2000** [walterbender/turtleblocksjs#356] opened 2018-03-14 13:56 UTC
![image](https://user-images.githubusercontent.com/10228651/37406382-083cda9e-27bd-11e8-8e6b-2797d0d59e63.jpg)
![image1](https://user-images.githubusercontent.com/10228651/37406546-6c845ef0-27bd-11e8-984b-66ce23c14ac5.jpg)
The existing background color of the Turtle Blocks is in the blue color which get emerged with the other colors scheme like palette icons. So this does not catch much eyes on the palette icons which is our first step to code so for this in the image i have attached , i have made the background color to 80% black and grey due to which it enhances the other colors of icons on it  and look attractive. Moreover it makes the color combination good. 
Even when blocks are placed on it, looks good making the good color schemes.

**Comment by walterbender** [comment] 2018-03-15 22:43
This is a duplicate of https://github.com/walterbender/musicblocks/issues/714

**Closed by walterbender** 2018-03-15 22:43 UTC
