### ISSUE TITLE
Can't edit values of number or text blocks in Chrome

### ISSUE THREAD

**Issue by cgreenhill** [walterbender/turtleblocksjs#275] opened 2016-06-07 21:52 UTC
When running Turtle Blocks JS in a Chrome browser from index.html or the Sugar Labs server, the values of text and number blocks can't be edited. This doesn't seem to be an issue if run from a local server or if opened in Firefox.

**Comment by walterbender** [comment] 2016-06-08 01:31
I cannot reproduce this error, but it could be that I have trained myself to click on the text in a particular way. You need to click on the text itself. (Maybe I can fix that.) Is there anything in the console?

**Comment by cgreenhill** [comment] 2016-06-08 18:37
I finally found a way to reliably reproduce the issue:

Open Chrome, load http://walterbender.github.io/turtleblocksjs/
Add a "forward" block
Click the "Run Fast" button
Open a new tab
Google search ("turtles")
Click on any link
Switch back to Turtle Blocks tab
Try to edit the value for the "forward" block

Running the latest version of Chrome (51.0.2704.84 m) with all extensions disabled
Windows 8.1

**Comment by cgreenhill** [comment] 2016-06-08 18:38
Here's the console log:

SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
platformstyle.js:25 On platform:  Object
p5.sound.js:176 Uncaught InvalidAccessError: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.
activity.js:111 innerWidth: 1008 innerHeight: 1055 outerWidth: 1024 outerHeight: 1144 
activity.js:223 on XO? false
logo.js:94 The microphone is not available.
activity.js:1148 Resize: scale 1.1722222222222223, windowW 1008, windowH 1055, canvasW 1008, canvasH 1055, screenW 1024, screenH 1280
activity.js:2058 1.1722222222222223
activity.js:1549  LOAD START
activity.js:1571 restoring session: [[0,["start",{"collapsed":false,"xcor":0,"ycor":707,"heading":0,"color":0,"shade":50,"pensize":5,"grey":100}],250,145,[null,1,null]],[1,["forward",{}],263.5,185.5,[0,2,null]],[2,["number",{"value":101}],343,185.5,[1]]]
blocks.js:2542 3 blocks to load
turtle.js:1011 adding a new turtle start
activity.js:1388 overwriting session data
logo.js:401 running from turtle 0
activity.js:1388 overwriting session data

**Comment by walterbender** [comment] 2016-06-08 20:57
Hmm. I cannot reproduce the problem with Chrome on a GNU/Linux machine. I'll try to get my hands on a Windows box to test.

**Comment by cgreenhill** [comment] 2016-06-08 21:10
Well, after restarting my machine, the steps above no longer reproduce the issue. I have had other people report the same issue to me, though.

**Comment by walterbender** [comment] 2016-06-08 21:12
There is nothing worse than a sporadic bug. I will keep trying to reproduce it.

**Comment by tradzik** [comment] 2017-01-01 15:49
After following @cgreenhill steps I do experience this bug almost every time I use TBJS on Chorme. Definitely has to be investigated further.

**Comment by walterbender** [comment] 2017-01-01 16:21
I still cannot reproduce this :(

**Comment by Tabs16** [comment] 2017-01-02 16:29
@tradzik @walterbender I followed the steps stated by @cgreenhill but unable to reproduce the issue on Chrome on a GNU/Linux machine,seems like it can be dependant on OS.

**Comment by tradzik** [comment] 2017-01-06 17:26
Could be related to #236 . On Chrome on Android no block editions seem to work.

**Comment by tradzik** [comment] 2017-01-07 14:24
Fixed in #311 .

**Closed by tradzik** 2017-01-07 14:24 UTC
Labels: bug, major
