### ISSUE TITLE
Horizontal bar appears while loading Turtle Blocks

### ISSUE THREAD

**Issue by aditodkar** [walterbender/turtleblocksjs#328] opened 2017-03-21 11:55 UTC
![screenshot_0](https://cloud.githubusercontent.com/assets/16613832/24146343/56972c02-0e5b-11e7-82ac-f181ad375e1e.png)

**Comment by samswag** [comment] 2017-03-21 12:08
<img width="1280" alt="screen shot 2017-03-21 at 1 06 16 pm" src="https://cloud.githubusercontent.com/assets/6048601/24146755/5d97c21a-0e37-11e7-85bc-7a8f60bb02bd.png">

Mine looks good from Google Chrome (Macbook)

**Comment by aditodkar** [comment] 2017-03-21 13:10
I can still see it in my chrome browser on windows.

**Comment by eohomegrownapps** [comment] 2017-10-27 22:28
To the best of my knowledge, the problem, to do with the visibility of the `statusmatrix` div, appears to be fixed in the walterbender/turtleblocksjs git repo - however, turtle.sugarlabs.org (the site from which the problem is sporadically experienced) is not running the latest version of Turtle Blocks.

**Comment by walterbender** [comment] 2017-12-15 19:05
I updated the repo on t.sl.o.

**Closed by walterbender** 2017-12-15 19:05 UTC
