### ISSUE TITLE
Making the palette icons into two columns

### ISSUE THREAD

**Issue by jaskirat2000** [walterbender/turtleblocksjs#357] opened 2018-03-14 14:04 UTC
images for this can be seen here : 
(https://wiki.sugarlabs.org/images/3/3d/IMAGE.jpg ) 
( https://wiki.sugarlabs.org/images/f/f1/Image1.jpg )

As by making the palette icons into columns, it will replace the need to scroll for finding the icons. So proper size base boxes could be made that would help to hold equal size icons in it.

**Comment by walterbender** [comment] 2018-03-15 22:43
This is a duplicate of https://github.com/walterbender/musicblocks/issues/822

**Closed by walterbender** 2018-03-15 22:43 UTC
